homepage/urls.py
from django.urls import path
from . import views
from django.contrib import admin

app_name = 'homepage'

urlpatterns = [
    path('', views.story3, name='story3'),
    path('profilepage/', views.profilepage, name='profilepage'),
    path('experience/', views.experience, name='experience'),
    path('portfolio/', views.portfolio, name='portfolio'),
    path('seefriend/', views.seefriend, name='seefriend'),
    path('addfriend/', views.addfriend, name='addfriend'),
    path('seefriend/deletefriend/<str:name>', views.deletefriend, name='deletefriend'),
    # dilanjutkan ...
]

story/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('homepage.urls')),
]

homepage/models.py
from django.db import models
from django.forms import ModelForm

#Create your models here.
class ClassYear(models.Model):
    BATCH_CHOICES= [('Maung (2019)', 'Maung (2019)'),
    ('Quanta (2018)', 'Quanta (2018)'),
    ('Tarung (2017)', 'Tarung (2017)'),
    ('Omega (2016)', 'Omega (2016)'),
    ('Others', 'Others')]
    batch = models.CharField(max_length=255, choices=BATCH_CHOICES, default='NULL')

    def __str__(self):
        return self.batch

class Friends(models.Model):
    name = models.CharField(max_length=255, primary_key=True)
    ClassYear = models.ForeignKey(ClassYear, on_delete=models.CASCADE, default='Fasilkom')
    hobby = models.CharField(max_length=255)
    food = models.CharField(max_length=255)
    drink = models.CharField(max_length=255)


    def __str__(self):
        return self.name

homepage/forms.py
from django import forms
from .models import Friends, ClassYear

class FriendForm(forms.ModelForm):
    
    class Meta:
        model = Friends
        fields = ['name', 
        'ClassYear', 
        'hobby', 
        'food', 
        'drink']
        labels = {'name': 'Name',
        'ClassYear': 'Batch',
        'hobby': 'Hobby',
        'food': 'Favorite Food',
        'drink': 'Favorite Drink',
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.Meta.fields:
            self.fields[field].widget.attrs.update({
                'class': 'form-control'
            })

homepage/views.py
from django.shortcuts import render
from django.shortcuts import redirect
from .models import Friends, ClassYear
from . import forms

# Create your views here.
def story3(request):
    return render(request, 'story3.html')

def profilepage(request):
    return render(request, 'profilepage.html')

def experience(request):
    return render(request, 'experience.html')

def portfolio(request):
    return render(request, 'portfolio.html')

def seefriend(request):
    friends = Friends.objects.all()
    classyear = ClassYear.objects.all()
    response = {'friends' : friends, 'classyear': classyear}
    return render(request, 'seefriend.html', response)

def addfriend(request):
    if request.method == 'POST':
        form = forms.FriendForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('homepage:seefriend')
    else:
        form = forms.FriendForm()
    return render(request, 'addfriend.html', {'form': form})

def deletefriend(request, name):
    friends = Friends.objects.get(name=name)
    friends.delete()
    return redirect('/seefriend/')

homepage/templates/addfriend.html
{% extends 'navbar.html' %}

{% load static %}

{% block content %}
<title>Add Friends</title>
<br><br><br><br>
<h1 id="profh1">Add Friends</h1>

<form method="post" action="{% url 'homepage:addfriend' %}">
    {% csrf_token %}
    <div style="margin-left: 10px; margin-right: 10px;">
    <div class="form-row">
        <div class="col-sm-1"></div>
        <div class="form-group col-sm-10">
            {% for fields in form %}
                {{ fields.label_tag }}
                <br>
                {{ fields }}
            {% endfor %}
        </div>
    </div>
    <div class="form-row">
        <input id="submitBtn" type="submit" class="btn btn-primary" value="Add">
    </div>
</form>
</div>

{% endblock %}

homepage/templates/copyright.html
<br><br>
<footer>
    <h2 style="font-size: 10px; text-align: center;"> © Tsamara Esperanti E 2020</h2>
</footer>

homepage/templates/experience.html
{% extends 'navbar.html' %}
{% load static %}

{% block content %}
<title>Experience</title>
      <div class="marg">
      <div id="carouselExampleControls" class="carousel slide" data-ride="carousel">
        <div class="carousel-inner">
          <div class="carousel-item active">
            <h1 style="font-size: 50px; text-shadow: -4px 3px 2px #E89DA2;">
                Education</h1> <br>
            <div class="box2">
                <div class="row" style="float: center;">
                    <div class="col-sm-3" style="float: right; padding-top:10px">
                        <img src="{% static 'images/makara.png' %}" alt="kuliah" style="max-width: 75px;">
                    </div>
                    <div class="col-sm-8" style="float: left; text-align: left; 
                    padding-left: 3px; padding-top:15px">
                        <h3 class="h3exp">
                            Faculty of Computer Science Universitas Indonesia</h3>
                        <p>2018 - Present</p> <br>
                    </div>
                  </div>
                  <div class="row" style="float: center;">
                    <div class="col-sm-3" style="float: right;">
                        <img src="{% static 'images/labschool.png' %}" alt="sma" style="max-width:75px;">
                    </div>
                    <div class="col-sm-8" style="float: left; text-align: left; 
                    padding-left: 3px;">
                        <h3 class="h3exp" style="padding-top:7px">
                        SMA Labcshool Kebayoran </h3>
                        <p>2015 - 2018</p><br>
                    </div>
                  </div>
                  <div class="row" style="float: center;">
                    <div class="col-sm-3" style="float: right;">
                        <img src="{% static 'images/labschool.png' %}" alt="smp" style="max-width:75px">
                    </div>
                    <div class="col-sm-8" style="float: left; text-align: left; 
                    padding-left: 3px;">
                        <h3 class="h3exp" style="padding-top:7px">
                            SMP Labschool Kebayoran</h3>
                        <p> 2013 - 2015</p>
                    </div>
                  </div>
            </div>
          </div>
          <div class="carousel-item">
            <h1 style="font-size: 50px; text-shadow: -4px 3px 2px #E89DA2;">
                Experience</h1> <br>
            <div class="box2" style="padding-left: 100px;">
                <div class="container">
                    <div class="row">
                      <div class="col" style="padding-top:15px">
                            <img src="{% static 'images/money.png' %}" alt="money" style="max-width: 50px;">
                            <h3 class="font20">
                            Vice Person in Charge of Fundraising</h3>
                            <p>
                            COMPFEST 12 <br>
                            2020 </p> 
                        </div>
                        <div class="col">
                            <img src="{% static 'images/algebra.png' %}" alt="algebra" style="max-width: 55px;">
                            <h3 style="font-size: 22px;" style="padding-top:15px">
                            Linear Algebra Teaching Assistant </h3>
                            <p>
                            Fasilkom UI <br>
                            2020 </p> 
                        </h3>
                        </div>
                      </div>
                      <div class="row">
                      <div class="col">
                        <img src="{% static 'images/contract.png' %}" alt="doc" id="pad" style="max-width: 50px;">
                        <h3 class="font20">
                            <b> Staff of Editorial Marketing </b> </h3>
                        <p>
                        COMPFEST 11 <br>
                        2019 </p>
                      </div>
                      <div class="col">
                        <img src="{% static 'images/camera.png' %}" alt="make up" style="max-width: 50px;">
                        <h3 class="font20">
                            Staff of Documentation</h3>
                        <p>
                        OH Fasilkom UI<br>
                        2019 </p>
                        </h3>
                      </div>
                      </div>
                    </div>
                </div>
          </div>
          <div class="carousel-item">
            <h1 style="font-size: 50px; text-shadow: -4px 3px 2px #E89DA2;">
                Skills</h1> <br>
            <div class="box2">
                <div class="container">
                    <div class="row">
                      <div class="col" style="padding-top: 20px;">
                        <img class="skills" src="{% static 'images/java.png' %}" alt="java">
                        <h2 style="text-align: center; font-size: 25px;">Java</h2>
                        </div>
                        <div class="col" style="padding-top: 20px;">
                        <img class="skills" src="{% static 'images/sql.png' %}" alt="sql">
                        <h2 style="text-align: center; font-size: 25px;">SQL</h2>
                      </div>
                    </div>
                    <div class="row">
                      <div class="col" style="padding-top: 20px;">
                        <img class="skills" src="{% static 'images/py.png' %}" alt="py">
                        <h2 style="text-align: center; font-size: 23px;">Python</h2>
                      </div>
                      <div class="col" style="padding-top: 20px;">
                        <img class="skills" src="{% static 'images/html.png' %}" alt="html">
                        <h2 style="text-align: center; font-size: 23px;">HTML</h2>
                      </div>
                    </div>
            </div>
          </div>
        </div>
        <a class="carousel-control-prev" href="#carouselExampleControls" role="button" data-slide="prev">
          <span class="carousel-control-prev-icon" aria-hidden="true"></span>
          <span class="sr-only">Previous</span>
        </a>
        <a class="carousel-control-next" href="#carouselExampleControls" role="button" data-slide="next">
          <span class="carousel-control-next-icon" aria-hidden="true"></span>
          <span class="sr-only">Next</span>
        </a>
      </div>
      <br>
    </div>
    <br>
{% endblock %}

homepage/templates/navbar.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css?family=Montserrat&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Abril+Fatface&display=swap" rel="stylesheet">
</head>

<body id="page-top">
<nav id="thisnav" class="navbar fixed-top navbar-expand-lg navbar-light" style="background-color: #FEF7E5; min-height: 80px;">
        TSAMARA E. ERWIN
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
          <ul class="navbar-nav ml-auto">
            <li class="nav-item">
              <a class="nav-link" href="{% url 'homepage:story3' %}">Home <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'homepage:profilepage' %}">Profile</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'homepage:experience' %}">Experience</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'homepage:portfolio' %}">Portfolio</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'homepage:seefriend' %}">Friends</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#" data-toggle="modal" data-target="#Modal">Contact Me</a>
            </li>
          </ul>
        </div>
      </nav>
      <!-- Challenge -->
      <div class="modal fade" id="Modal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
          <div class="modal-content">
            <div class="modal-header">
              <h5 class="modal-title" id="exampleModalLabel">Reach me out through:</h5>
              <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
              </button>
            </div>
            <div class="modal-body" style="text-align: center;">
              <a href="https://www.instagram.com/sarahesperanti" style="text-decoration: none; text-align: center;"> 
                <img src="{% static 'images/Instagram.png' %}" alt="ig" class="modalpic"> 
              </a>
              <a href="https://www.linkedin.com/in/tsamara-esperanti-erwin" style="text-decoration: none; text-align: center;"> 
                <img src="{% static 'images/linkedin.png' %}" alt="linkedin" class="modalpic"> 
            </a>  
            <a href="https://www.twitter.com/estsamara" style="text-decoration: none; text-align: center;"> 
              <img src="{% static 'images/twitter.png' %}" alt="twt" class="modalpic"> 
          </a>  
            </div>
            <div class="modal-footer">
              <button type="button" class="btn btn-secondary" data-dismiss="modal" style="background-color: #FEF7E5; color: black;">Close</button>
            </div>
          </div>
        </div>
      </div>
      {% block content %}

      {% endblock %}
      
      {% include 'copyright.html' %}
    
      <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
      <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
      <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
    </body>
</html>

homepage/templates/portfolio.html
{% extends 'navbar.html' %}
{% load static %}

{% block content %}
<title>Portfolio</title>
<div class="marg">
      <h1 id="h1port"> design and things that i love </h1>
      <br>
      <div class="container">
        <div class="row">
          <div class="col">
            <div class="box" style="height: 188px;">
                <h2 style="font-size: 30px; text-align: 
                center; padding-top: 1px; padding-bottom: 1px;margin-top: -30px;
                font-family: Abril Fatface;">
                    EDITING SKILLS</h2>
                    <div class="container">
                        <div class="row">
                          <div class="col">
                            <img class="skills" src="{% static 'images/imovie.png' %}" alt="imovie" style="max-width: 45px;">
                            <h2 style="text-align: center; font-size: 20px;">iMovie / Final Cut Pro</h2>
                          </div>
                          <div class="col" style="padding-left: 30px;">
                            <img class="skills" src="{% static 'images/photoshop.png' %}" alt="photoshop" style="max-width: 45px;">
                            <h2 style="text-align: center; font-size: 20px;">Adobe Photoshop</h2>
                          </div>
                     </div>
                </div> 
              </div>
              <br>
              <div>
                  <h1 style="font-size: 30px; text-shadow: -4px 3px 2px #E89DA2;">K-DESIGNS</h1>
                  <div class="box" style="text-align: center;">
                    <img src="{% static 'images/20190827.png' %}" alt="sticker" style="max-width: 200px;">
                    <br>
                    <br>
                    <img src="{% static 'images/slogan.png' %}"" alt="slogan" style="max-width: 200px;">
                  </div>
              </div>  
                    <br>
          </div>
          <div class="col-sm-1"></div>
          <div class="col">
            <div class="box" style="text-align: center;">
              <h2 style="font-size: 30px; text-align: 
              left; padding-top: 1px; margin-top: -30px;
              font-family: Abril Fatface;">
                  LETTERING</h2>
                  <img src="{% static 'images/L3.jpg' %}" alt="L3" style="max-width: 200px;">
                  <br><br>
                  <img src="{% static 'images/L1.jpg' %}" alt="L1" style="max-width: 200px;">
                  <br><br>
                  <img src="{% static 'images/L2.jpg' %}" alt="L2" style="max-width: 200px;">
                </div>
                <br><br>
                <h1 style="text-align: center; font-size: 60px; padding-left: 20px; text-shadow: -4px 3px 2px #E89DA2;"> 
                  See more of my portfolio 
                  <a href="https://instagram.com/teetypes" style="color: #FEF7E5; text-shadow: 0px 0px 0px; text-decoration: none;"> here.</a>
                </h1>
            </div>
            <br>
          </div>
        </div>
    </div>
  </div>
{% endblock %}

homepage/templates/profilepage.html
{% extends 'navbar.html' %}
{% load static %}

{% block content %}
<title>Profile</title>
<div class="marg">
  <h1 id="profh1"> Tsamara Esperanti Erwin </h1>
      <br>
      <br>
      <div class="container">
        <div class="row">
          <div class="col">
            <h2 class= "box" style="text-align: right;">
                Hello! My name is Sarah. 
                I'm currently a second-year Computer Science undergraduate in
                Universitas Indonesia. I'm a passionate and hard-working person
                who's seeking more experience in IT-related field. I'd love to learn
                more about data science and UI/UX.
            </h2>
          </div>
          <div class="col">
            <div style="
            padding-left: 20px;
            padding-right: 20px;
            padding-top: 5px; padding-bottom: 15px;">
            <img class="profilePhoto" src="{% static 'images/profile.JPG' %}" alt="me">
          </div>
          </div>
          <div class="col">
            <h2 class="box" style="font-size: 20px; text-align: center;"> 
                Let's stay in touch.
                <br>
                <br>
            <a href="https://www.instagram.com/sarahesperanti" style="text-decoration: none;"> 
                <button id="socmed" type="button" class="btn btn-light">
                <img src="{% static 'images/Instagram.png' %}" alt="ig" style="max-width: 30px;"> 
                @sarahesperanti </button> 
            </a> 
            <br>
            <a href="https://www.linkedin.com/in/tsamara-esperanti-erwin" style="text-decoration: none;"> 
                <button id="socmed" type="button" class="btn btn-light">
                <img src="{% static 'images/linkedin.png' %}" alt="linkedin" style="max-width:30px;">
                Tsamara Esperanti Erwin </button> 
            </a> 
            <br>
            <a href="https://www.twitter.com/estsamara" style="text-decoration: none;"> 
              <button id="socmed" type="button" class="btn btn-light">
              <img src="{% static 'images/twitter.png' %}" alt="twitter" style="max-width:30px;">
              @estsamara </button> 
            </a> 
            <br>
            <p style="font-size: 20px; text-align: center;">
             or send me 
                <a href="mailto:sarah.esperanti@gmail.com" style="color: gray; text-decoration: none;"> 
                an email.
            </a>
            </p>
            </h2>
          </div>
        </div>
      </div>
    </div>
 {% endblock %}

homepage/templates/seefriend.html
{% extends 'navbar.html' %}

{% load static %}

{% block content %}
<title>See Friends</title>
<br><br><br><br>
<h1 id="profh1">My Friends</h1>
<br>
<div id="carouselExampleControls" class="carousel slide" data-ride="carousel">
  <div class="carousel-inner">
      {% for friend in friends %}
          <div class="carousel-item {% if forloop.counter == 1 %}active{% endif %}" id="slide{{ forloop.counter }}">
              <div class="box3">
                <br>
                <div class="container">
                  <div class="row">
                    <div class="col-sm-2" style="margin-left: 60px;">
                      <img src="{% static 'images/user.png' %}" alt="name" style="max-width:40px;">
                    </div>
                    <div class="col-sm">
                      <h2>{{ friend.name }}</h2>
                    </div>
                  </div>
                  <div class="row">
                    <div class="col-sm-2" style="margin-left: 60px;">
                      <img src="{% static 'images/mortarboard.png' %}" alt="batch" style="max-width:40px;">
                    </div>
                    <div class="col-sm">
                      <h2>{{ friend.ClassYear }}</h2>
                    </div>
                  </div>
                  <div class="row">
                    <div class="col-sm-2" style="margin-left: 60px;">
                      <img src="{% static 'images/puzzle.png' %}" alt="hobby" style="max-width:40px;">
                    </div>
                    <div class="col-sm">
                      <h2>{{ friend.hobby }}</h2>
                    </div>
                  </div>
                  <div class="row">
                    <div class="col-sm-2" style="margin-left: 60px;">
                      <img src="{% static 'images/dish.png' %}" alt="food" style="max-width:40px;">
                    </div>
                    <div class="col-sm">
                      <h2>{{ friend.food }}</h2>
                    </div>
                  </div>
                  <div class="row">
                    <div class="col-sm-2" style="margin-left: 60px;">
                      <img src="{% static 'images/coffee-cup.png' %}" alt="food" style="max-width:40px;">
                    </div>
                    <div class="col-sm">
                      <h2>{{ friend.drink }}</h2>
                    </div>
                  </div>
                  </div>
                  <br>
                  <a href="/seefriend/deletefriend/{{friend.name}}"><button type ="button" class="btn btn-danger btn-sm mt-3">
                    Delete</button></a>
                </div>
          </div>
      {% endfor %}
  </div>
  <a class="carousel-control-prev" href="#carouselExampleControls" role="button" data-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="carousel-control-next" href="#carouselExampleControls" role="button" data-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>
<h2 style="color: #FEF7E5; text-align:center; font-size: 15px; margin-top: 15px;">
  click the arrows to see more!</h2>
<a href="{% url 'homepage:addfriend' %}" style="text-decoration: none;"> 
  <button id="friendButton" type="button" class="btn btn-light">
    Add Friends</button> </a>


{% endblock %}

homepage/templates/story3.html
{% extends 'navbar.html' %}

{% load static %}
{% block content %}
<title>Homepage</title>
      <div class="container" style="align-items: center;">
        <div class="row">
          <div class="col head1">
            <h1 id="homeh1"> 
              Hi there,
              <br>
              I'm Sarah.
          </h1>
          <br>
            <a href="{% url 'homepage:profilepage' %}" style="text-decoration: none;"> 
              <button id="b1" type="button" class="btn btn-light">
                Get to know me! </button> </a>
          </div>
          <div class="col head1" style="margin-top: 20px">
            <img src="{% static 'images/profpic.png' %}" alt="my photo" id="homepic">
          </div>
        </div>
        </div>
        <div class="container">
          <div class="row" style="margin-bottom: 2px;">
            <div class="col">
              <a href="{% url 'homepage:seefriend' %}" style="text-decoration: none;"> 
                <button id="friendButton" type="button" class="btn btn-light">
                  See Friends </button> </a>
            </div>
            <div class="col">
              <a href="{% url 'homepage:addfriend' %}" style="text-decoration: none;"> 
                <button id="friendButton" type="button" class="btn btn-light">
                  Add Friends </button> </a>
            </div>
          </div>
        </div>
{% endblock %}